/**
 * Flat Weblate-friendly catalog (ADR 0013); keys stay sorted.
 *
 * Good-faith draft translation, to be refined by the community via
 * Weblate. Report awkward phrasings rather than working around them.
 */
export const de = {
  account: 'Konto',
  accountOptional:
    'Lernen funktioniert auch ohne Konto — ein Konto synchronisiert nur deinen Fortschritt zwischen Geräten.',
  aiDisclosure: 'KI-Entwurf, von Menschen geprüft',
  allDone: 'Alles fertig.',
  allReviewed: 'Alles wiederholt.',
  answered: '{count} beantwortet',
  approve: 'Freigeben',
  assemblyBankAria: 'Wortvorrat',
  assemblyBuiltAria: 'Dein Satz',
  assemblyKind: 'Satz bauen',
  audioConsentAgree: 'Zustimmen und aufnehmen',
  audioConsentApp: 'App-Nutzung',
  audioConsentAppNote:
    'Erlaube der App, deine Aufnahme mit anderen Lernenden zu teilen. Für das Aufnehmen erforderlich.',
  audioConsentDataset: 'Offener Sprachdatensatz',
  audioConsentDatasetNote:
    'Nimm deine Aufnahme in einen gemeinsamen Sprachdatensatz auf, der kommerziell lizenziert werden kann. Aus, bis du es einschaltest.',
  audioConsentIntro:
    'Wähle, wie deine Stimme genutzt werden darf. Jede Wahl ist getrennt, und du kannst sie später ändern.',
  audioConsentRequired: 'Erforderlich',
  audioConsentTitle: 'Bevor du aufnimmst',
  audioConsentTraining: 'Training von Sprachmodellen',
  audioConsentTrainingNote:
    'Lass deine Aufnahme helfen, Sprachmodelle zu trainieren, zusammen mit vielen anderen — niemals um deine Stimme zu klonen. Aus, bis du es einschaltest.',
  audioCreditLine:
    '{seconds} Sekunden bestätigt → {days} Premium-Tage verdient',
  audioCreditNone:
    'Noch keine Premium-Zeit — Aufnahmen verdienen sie, sobald die Community sie bestätigt.',
  audioCreditTitle: 'Verdiente Premium-Zeit',
  audioReview: 'Sprachaufnahmen',
  audioStatusPending: 'Wartet auf Stimmen',
  audioStatusRejected: 'Nicht angenommen',
  audioStatusVerified: 'Bestätigt',
  audioWhatHappens: 'Was passiert mit meiner Stimme?',
  audioWhatHappensNote:
    'Deine Aufnahme wird unter einem Pseudonym gespeichert, nie unter deinem Namen. Die drei Optionen oben sind getrennt — App-Nutzung bedeutet nie Datensatz oder Training. Du kannst deine Einwilligung jederzeit widerrufen; das entfernt deine Stimme aus künftigen Datensatz-Versionen, doch bereits geteilte Versionen lassen sich nicht zurückrufen. Deine Stimme wird nie genutzt, um einen einzelnen Sprecher zu klonen.',
  back: '← Zurück',
  boardsCleared: 'Gelöste Tafeln: {count}',
  check: 'Prüfen',
  clozeLabel: 'Tippe das fehlende Wort — Sonderzeichen optional',
  codeLicense: 'Code: AGPL-3.0-only',
  commonWords: 'Häufige Wörter',
  communityReview: 'Community-Prüfung',
  contentLicense: 'Inhalte: CC BY-SA 4.0',
  continueButton: 'Weiter',
  contribute: 'Beitragen',
  contributeFailed: 'Senden fehlgeschlagen — versuche es gleich noch einmal.',
  contributeLicense:
    'Mit dem Senden stellst du deinen Beitrag unter CC BY-SA 4.0 — die offene Lizenz, die diesen Kurs frei teilbar hält.',
  contributeNote:
    'Alles, was du hinzufügst, geht vor der Veröffentlichung in die Community-Prüfung, unter CC BY-SA 4.0.',
  contributeTitle: 'Neuen Eintrag vorschlagen',
  contributed: 'Gesendet! Es wird bald geprüft.',
  correct: 'Richtig!',
  createAccount: 'Konto erstellen',
  createTitle: 'Ein Konto erstellen',
  deleteAccount: 'Mein Konto löschen',
  deleteConfirm: 'Noch einmal drücken, um alles zu löschen',
  deleteFailed: 'Löschen fehlgeschlagen — versuche es gleich noch einmal.',
  dialogueBankAria: 'Dialogzeilen',
  dialogueBuiltAria: 'Dein Dialog',
  dialogueReorderKind: 'Dialog neu aufbauen',
  dismiss: 'Schließen',
  displayName: 'Anzeigename',
  displayScript: 'Anzeigeschrift',
  downloadData: 'Meine Daten herunterladen',
  email: 'E-Mail',
  erasedNotice:
    'Dein Konto und seine Daten sind gelöscht. Der lokale Fortschritt auf diesem Gerät bleibt erhalten.',
  exportFailed: 'Export fehlgeschlagen — versuche es gleich noch einmal.',
  fillBlank: 'Lücke füllen',
  formComparative: 'Komparativ',
  formPlural: 'Plural',
  formPresent1sg: 'Präsens „ich“',
  formPresent3pl: 'Präsens „sie“',
  formPrompt: 'Tippe die Form: {form}',
  formSuperlative: 'Superlativ',
  goalActiveDays: 'Aktive Tage',
  goalJournal: 'Tagebucheinträge',
  goalProgress: '{done} / {total}',
  goalReviews: 'Wiederholungen',
  goalsTitle: 'Diese Woche',
  growingCourseBanner:
    'Jeden Monat neue Einheiten — hilf mit, es wachsen zu lassen.',
  haveAccount: 'Schon ein Konto? Anmelden',
  incorrect: 'Nicht ganz.',
  interfaceLanguage: 'Oberflächensprache',
  journalLabel: 'Schreib ein paar Zeilen',
  journalPrompt1: 'Was hast du heute gemacht?',
  journalPrompt2: 'Beschreibe etwas in deiner Nähe.',
  journalPrompt3: 'Wofür bist du heute dankbar?',
  journalPrompt4: 'Schreib über jemanden, mit dem du gesprochen hast.',
  journalPrompt5: 'Was möchtest du morgen tun?',
  journalSave: 'Heutigen Eintrag speichern',
  journalSaved: 'Gespeichert. Gut gemacht heute.',
  journalSuggested: 'Versuch, diese Wörter einzubauen',
  journalTitle: 'Tagebuch',
  kindLabel: 'Typ',
  kindPhrase: 'Wendung',
  kindSentence: 'Satz',
  kindWord: 'Wort',
  languageSwitch: 'Sprache wechseln',
  lessonWords: '{count} Wörter',
  listen: 'Anhören',
  listeningKind: 'Hörverstehen',
  listeningPrompt: 'Tippe, was du hörst',
  loading: 'Lädt…',
  manageUsers: 'Nutzer verwalten',
  matchPairs: 'Paare finden',
  missingWordAria: 'fehlendes Wort',
  morphologyKind: 'Wortformen',
  myRecordings: 'Meine Aufnahmen',
  myRecordingsEmpty: 'Du hast noch keine Aufnahmen geteilt.',
  newHere: 'Neu hier? Konto erstellen',
  noCourse: 'Noch kein Kurs — der Grundstock ist unterwegs.',
  noDrafts: 'Keine Entwürfe warten auf Prüfung.',
  noVotes: 'Nichts wartet auf Stimmen.',
  notCanonical:
    'Verwende die albanische Standardorthographie — Buchstaben wie ë und ç sind willkommen.',
  nothingDue: 'Gerade ist nichts fällig. Schau später wieder vorbei.',
  nothingWeak: 'Noch keine schwachen Wörter — lerne weiter.',
  onboardLanguage: 'Welche Sprache sprichst du schon?',
  onboardNote: 'Kein Konto nötig — dein Fortschritt bleibt auf diesem Gerät.',
  onboardTitle: 'Willkommen',
  openNumbers: 'Offene Zahlen',
  password: 'Passwort',
  planPickUnit: 'Schwerpunkt-Einheit',
  planRestNote: 'Ruh dich aus — du hast es verdient.',
  practiceTitle: 'Üben',
  productionKind: 'Schreib selbst',
  productionMiss: 'Verwende jedes vorgegebene Wort, kanonisch geschrieben.',
  productionPrompt: 'Schreib einen Satz mit diesen Wörtern',
  progressFollows: 'Dein Fortschritt begleitet dich jetzt über alle Geräte.',
  record: 'Aufnehmen',
  recordingFailed: 'Die Aufnahme konnte nicht gespeichert werden.',
  recordingSaved: 'Aufnahme geteilt — danke.',
  reject: 'Ablehnen',
  reviewDecided: '{count} entschieden',
  reviewDrafts: 'Entwürfe prüfen',
  reviewUnavailable:
    'Die Prüfliste ist nicht erreichbar — bist du als Admin angemeldet?',
  roleAdmin: 'Admin',
  roleLabel: 'Rolle',
  roleLearner: 'Lernende:r',
  roleReviewer: 'Prüfer:in',
  scriptDrillKind: 'Schrift-Übung',
  scriptTypeIn: 'Tippe es in {script}',
  secondsLeft: 'Noch {count} s',
  selfRateAgain: 'Nochmal üben',
  selfRateGood: 'Sitzt',
  sendForReview: 'Zur Prüfung senden',
  settings: 'Einstellungen',
  signInFailed: 'Falsche E-Mail oder falsches Passwort.',
  signInIssue:
    'Das hat nicht geklappt — prüfe die Angaben und versuche es noch einmal.',
  signInTitle: 'Anmelden',
  signInToContribute: 'Melde dich an, um beizutragen.',
  signInToVote: 'Melde dich an, um abzustimmen.',
  signOut: 'Abmelden',
  signUpFailed:
    'Konto konnte nicht erstellt werden — die E-Mail ist vielleicht vergeben, oder das Passwort ist kürzer als 8 Zeichen.',
  speedReview: 'Schnelles Wiederholen',
  startExercises: 'Übungen starten',
  startLearning: 'Jetzt lernen',
  statItems: 'Wörterbucheinträge',
  statLearners: 'Lernende',
  statReviews: 'Beantwortete Wiederholungen',
  statTranslations: 'Übersetzungen',
  statsNote:
    'Alles aggregiert, nichts Persönliches — das Projekt in der Öffentlichkeit.',
  stopRecording: 'Stopp',
  streak: 'Serie: {count} Tage',
  submitReview: 'Zur Community-Prüfung senden',
  switchDirection: 'Lernrichtung wechseln',
  switchScript: 'Schrift wechseln',
  syncedDown: '{count} Wiederholungen kamen von deinen anderen Geräten.',
  syncedReviews: '{count} neue Wiederholungen von diesem Gerät synchronisiert.',
  tagline: 'Albanisch lernen',
  targetLanguageAria: 'Albanisch',
  targetTextLabel: 'Albanisch (Standardorthographie)',
  taskJournal: 'Schreib einen Tagebucheintrag',
  taskReviewWeak: 'Wiederhole deine schwachen Wörter',
  taskReviews: 'Beantworte {count} Wiederholungen',
  taskStudyUnit: 'Lerne die Einheit {unit}',
  tasksCompleted: '{count} Aufgaben erledigt',
  theme: 'Design',
  themeDark: 'Dunkel',
  themeLight: 'Hell',
  themeSystem: 'System',
  timeUp: 'Die Zeit ist um.',
  toggleTheme: 'Design umschalten',
  translationLabel: 'Englische Übersetzung',
  translationLanguage: 'Übersetzungssprache',
  translationsAria: 'Übersetzungen',
  typedLabel: 'Tippe es auf Albanisch — Sonderzeichen optional',
  unreachable:
    'Der Server ist nicht erreichbar — versuche es gleich noch einmal.',
  unreachableNow: 'Der Server ist gerade nicht erreichbar.',
  usersUnavailable:
    'Die Nutzerliste ist nicht erreichbar — bist du als Admin angemeldet?',
  voteDown: 'Dagegen stimmen',
  voteUp: 'Dafür stimmen',
  weakItems: 'Schwache Wörter',
  weekdayFri: 'Freitag',
  weekdayMon: 'Montag',
  weekdaySat: 'Samstag',
  weekdaySun: 'Sonntag',
  weekdayThu: 'Donnerstag',
  weekdayTue: 'Dienstag',
  weekdayWed: 'Mittwoch',
  weeklyPlanTitle: 'Wochenplan',
  welcome: 'Willkommen.',
} as const;
