/**
 * Flat Weblate-friendly catalog (ADR 0013); keys stay sorted.
 *
 * Good-faith draft translation, to be refined by the community via
 * Weblate. Report awkward phrasings rather than working around them.
 */
export const de = {
  account: 'Konto',
  accountOptional:
    'Lernen funktioniert auch ohne Konto — ein Konto synchronisiert nur deinen Fortschritt zwischen Geräten.',
  aiDisclosure: 'KI-Entwurf, von Menschen geprüft',
  allDone: 'Gjithçka gati.',
  allReviewed: 'Gjithçka u përsërit.',
  answered: '{count} beantwortet',
  approve: 'Freigeben',
  assemblyBankAria: 'Wortvorrat',
  assemblyBuiltAria: 'Dein Satz',
  assemblyKind: 'Satz bauen',
  back: '← Zurück',
  boardsCleared: 'Gelöste Tafeln: {count}',
  check: 'Prüfen',
  clozeLabel: 'Tippe das fehlende Wort — Sonderzeichen optional',
  codeLicense: 'Code: AGPL-3.0-only',
  commonWords: 'Häufige Wörter',
  communityReview: 'Community-Prüfung',
  contentLicense: 'Inhalte: CC BY-SA 4.0',
  continueButton: 'Weiter',
  contribute: 'Beitragen',
  contributeFailed: 'Senden fehlgeschlagen — versuche es gleich noch einmal.',
  contributeLicense:
    'Mit dem Senden stellst du deinen Beitrag unter CC BY-SA 4.0 — die offene Lizenz, die diesen Kurs frei teilbar hält.',
  contributeNote:
    'Alles, was du hinzufügst, geht vor der Veröffentlichung in die Community-Prüfung, unter CC BY-SA 4.0.',
  contributeTitle: 'Neuen Eintrag vorschlagen',
  contributed: 'Gesendet! Es wird bald geprüft.',
  correct: 'Saktë!',
  createAccount: 'Konto erstellen',
  createTitle: 'Ein Konto erstellen',
  deleteAccount: 'Mein Konto löschen',
  deleteConfirm: 'Noch einmal drücken, um alles zu löschen',
  deleteFailed: 'Löschen fehlgeschlagen — versuche es gleich noch einmal.',
  dialogueBankAria: 'Dialogzeilen',
  dialogueBuiltAria: 'Dein Dialog',
  dialogueReorderKind: 'Dialog neu aufbauen',
  displayName: 'Anzeigename',
  downloadData: 'Meine Daten herunterladen',
  email: 'E-Mail',
  erasedNotice:
    'Dein Konto und seine Daten sind gelöscht. Der lokale Fortschritt auf diesem Gerät bleibt erhalten.',
  exportFailed: 'Export fehlgeschlagen — versuche es gleich noch einmal.',
  fillBlank: 'Lücke füllen',
  formComparative: 'Komparativ',
  formPlural: 'Plural',
  formPresent1sg: 'Präsens „ich“',
  formPresent3pl: 'Präsens „sie“',
  formPrompt: 'Tippe die Form: {form}',
  formSuperlative: 'Superlativ',
  haveAccount: 'Schon ein Konto? Anmelden',
  incorrect: 'Jo tamam.',
  kindLabel: 'Typ',
  kindPhrase: 'Wendung',
  kindSentence: 'Satz',
  kindWord: 'Wort',
  languageSwitch: 'Sprache wechseln',
  lessonWords: '{count} Wörter',
  listen: 'Anhören',
  listeningKind: 'Hörverstehen',
  listeningPrompt: 'Tippe, was du hörst',
  loading: 'Lädt…',
  manageUsers: 'Nutzer verwalten',
  matchPairs: 'Paare finden',
  missingWordAria: 'fehlendes Wort',
  morphologyKind: 'Wortformen',
  newHere: 'Neu hier? Konto erstellen',
  noCourse: 'Noch kein Kurs — der Grundstock ist unterwegs.',
  noDrafts: 'Keine Entwürfe warten auf Prüfung.',
  noVotes: 'Nichts wartet auf Stimmen.',
  notCanonical:
    'Verwende die albanische Standardorthographie — Buchstaben wie ë und ç sind willkommen.',
  nothingDue: 'Gerade ist nichts fällig. Schau später wieder vorbei.',
  nothingWeak: 'Noch keine schwachen Wörter — lerne weiter.',
  openNumbers: 'Offene Zahlen',
  password: 'Passwort',
  practiceTitle: 'Üben',
  productionKind: 'Schreib selbst',
  productionMiss: 'Verwende jedes vorgegebene Wort, kanonisch geschrieben.',
  productionPrompt: 'Schreib einen Satz mit diesen Wörtern',
  progressFollows: 'Dein Fortschritt begleitet dich jetzt über alle Geräte.',
  record: 'Aufnehmen',
  recordingFailed: 'Die Aufnahme konnte nicht gespeichert werden.',
  recordingSaved: 'Aufnahme geteilt — danke.',
  reject: 'Ablehnen',
  reviewDecided: '{count} entschieden',
  reviewDrafts: 'Entwürfe prüfen',
  reviewUnavailable:
    'Die Prüfliste ist nicht erreichbar — bist du als Admin angemeldet?',
  roleAdmin: 'Admin',
  roleLabel: 'Rolle',
  roleLearner: 'Lernende:r',
  roleReviewer: 'Prüfer:in',
  scriptDrillKind: 'Schrift-Übung',
  scriptTypeIn: 'Tippe es in {script}',
  secondsLeft: 'Noch {count} s',
  selfRateAgain: 'Nochmal üben',
  selfRateGood: 'Sitzt',
  sendForReview: 'Zur Prüfung senden',
  signInFailed: 'Falsche E-Mail oder falsches Passwort.',
  signInIssue:
    'Das hat nicht geklappt — prüfe die Angaben und versuche es noch einmal.',
  signInTitle: 'Anmelden',
  signInToContribute: 'Melde dich an, um beizutragen.',
  signInToVote: 'Melde dich an, um abzustimmen.',
  signOut: 'Abmelden',
  signUpFailed:
    'Konto konnte nicht erstellt werden — die E-Mail ist vielleicht vergeben, oder das Passwort ist kürzer als 8 Zeichen.',
  speedReview: 'Schnelles Wiederholen',
  startExercises: 'Übungen starten',
  startLearning: 'Jetzt lernen',
  statItems: 'Wörterbucheinträge',
  statLearners: 'Lernende',
  statReviews: 'Beantwortete Wiederholungen',
  statTranslations: 'Übersetzungen',
  statsNote:
    'Alles aggregiert, nichts Persönliches — das Projekt in der Öffentlichkeit.',
  stopRecording: 'Stopp',
  streak: 'Serie: {count} Tage',
  submitReview: 'Zur Community-Prüfung senden',
  switchScript: 'Schrift wechseln',
  syncedDown: '{count} Wiederholungen kamen von deinen anderen Geräten.',
  syncedReviews: '{count} neue Wiederholungen von diesem Gerät synchronisiert.',
  tagline: 'Albanisch lernen',
  targetLanguageAria: 'Albanisch',
  targetTextLabel: 'Albanisch (Standardorthographie)',
  timeUp: 'Die Zeit ist um.',
  toggleTheme: 'Design umschalten',
  translationLabel: 'Englische Übersetzung',
  translationLanguage: 'Übersetzungssprache',
  translationsAria: 'Übersetzungen',
  typedLabel: 'Tippe es auf Albanisch — Sonderzeichen optional',
  unreachable:
    'Der Server ist nicht erreichbar — versuche es gleich noch einmal.',
  unreachableNow: 'Der Server ist gerade nicht erreichbar.',
  usersUnavailable:
    'Die Nutzerliste ist nicht erreichbar — bist du als Admin angemeldet?',
  voteDown: 'Dagegen stimmen',
  voteUp: 'Dafür stimmen',
  weakItems: 'Schwache Wörter',
  welcome: 'Mirë se vini.',
} as const;
