/**
 * Flat Weblate-friendly catalog (ADR 0013); keys stay sorted.
 *
 * Good-faith draft translation, to be refined by the community via
 * Weblate. Report awkward phrasings rather than working around them.
 */
export const it = {
  account: 'Account',
  accountOptional:
    "Imparare funziona anche senza account — l'account serve solo a sincronizzare i progressi tra i dispositivi.",
  aiDisclosure: 'Bozza generata da IA, revisionata da persone',
  allDone: 'Tutto fatto.',
  allReviewed: 'Tutto ripassato.',
  answered: '{count} risposte',
  approve: 'Approva',
  assemblyBankAria: 'Parole disponibili',
  assemblyBuiltAria: 'La tua frase',
  assemblyKind: 'Componi la frase',
  audioConsentAgree: 'Accetta e registra',
  audioConsentApp: 'Uso nell’app',
  audioConsentAppNote:
    'Consenti all’app di condividere la tua registrazione con altri studenti. Necessario per registrare.',
  audioConsentDataset: 'Dataset vocale aperto',
  audioConsentDatasetNote:
    'Aggiungi la tua registrazione a un dataset vocale condiviso che può essere concesso in licenza commerciale. Disattivato finché non lo attivi.',
  audioConsentIntro:
    'Scegli come può essere usata la tua voce. Ogni scelta è separata e puoi cambiarla in seguito.',
  audioConsentRequired: 'Necessario',
  audioConsentTitle: 'Prima di registrare',
  audioConsentTraining: 'Addestramento di modelli vocali',
  audioConsentTrainingNote:
    'Permetti alla tua registrazione di aiutare ad addestrare modelli vocali, insieme a molte altre — mai per clonare la tua voce. Disattivato finché non lo attivi.',
  audioCreditLine:
    '{seconds} secondi convalidati → {days} giorni premium ottenuti',
  audioCreditNone:
    'Ancora nessun tempo premium — le registrazioni lo ottengono quando la comunità le convalida.',
  audioCreditTitle: 'Tempo premium ottenuto',
  audioReview: 'Registrazioni vocali',
  audioStatusPending: 'In attesa di voti',
  audioStatusRejected: 'Non accettata',
  audioStatusVerified: 'Convalidata',
  audioWhatHappens: 'Cosa succede alla mia voce?',
  audioWhatHappensNote:
    'La tua registrazione è conservata con uno pseudonimo, mai con il tuo nome. Le tre scelte qui sopra sono separate — l’uso nell’app non implica mai il dataset o l’addestramento. Puoi ritirare il consenso in qualsiasi momento: la tua voce viene rimossa dalle versioni future del dataset, anche se le versioni già distribuite non possono essere richiamate. La tua voce non viene mai usata per clonare un singolo parlante.',
  auditComment: 'Commento (facoltativo)',
  auditGoldenSet: 'Valuta il set aureo',
  axisAccuracy: 'Accuratezza',
  axisFit: 'Pertinenza',
  axisNaturalness: 'Naturalezza',
  back: '← Indietro',
  boardsCleared: 'Tabelloni risolti: {count}',
  check: 'Verifica',
  clozeLabel: 'Scrivi la parola mancante — gli accenti sono facoltativi',
  codeLicense: 'Codice: AGPL-3.0-only',
  commonWords: 'Parole frequenti',
  communityReview: 'Revisione della comunità',
  contentLicense: 'Contenuti: CC BY-SA 4.0',
  continueButton: 'Continua',
  contribute: 'Contribuisci',
  contributeFailed: 'Invio non riuscito — riprova tra poco.',
  contributeLicense:
    'Inviando, concedi il tuo contributo con licenza CC BY-SA 4.0 — la licenza aperta che mantiene questo corso libero di circolare.',
  contributeNote:
    'Tutto ciò che aggiungi passa dalla revisione della comunità prima della pubblicazione, con licenza CC BY-SA 4.0.',
  contributeTitle: 'Proponi una nuova voce',
  contributed: 'Inviato! Presto qualcuno lo revisionerà.',
  correct: 'Esatto!',
  createAccount: 'Crea account',
  createTitle: 'Crea un account',
  deleteAccount: 'Elimina il mio account',
  deleteConfirm: 'Premi di nuovo per cancellare tutto',
  deleteFailed: 'Eliminazione non riuscita — riprova tra poco.',
  dialogueBankAria: 'Battute del dialogo',
  dialogueBuiltAria: 'Il tuo dialogo',
  dialogueReorderKind: 'Ricostruisci il dialogo',
  dismiss: 'Chiudi',
  displayName: 'Nome visualizzato',
  displayScript: 'Alfabeto',
  downloadData: 'Scarica i miei dati',
  email: 'Email',
  erasedNotice:
    'Il tuo account e i suoi dati sono stati eliminati. I progressi locali su questo dispositivo restano intatti.',
  exportFailed: 'Esportazione non riuscita — riprova tra poco.',
  fillBlank: 'completa lo spazio',
  formComparative: 'comparativo',
  formPlural: 'plurale',
  formPresent1sg: 'presente «io»',
  formPresent3pl: 'presente «loro»',
  formPrompt: 'Scrivi la forma: {form}',
  formSuperlative: 'superlativo',
  goalActiveDays: 'Giorni attivi',
  goalJournal: 'Note del diario',
  goalProgress: '{done} / {total}',
  goalReviews: 'Ripassi',
  goalsTitle: 'Questa settimana',
  goldenAudited: '{count} valutati',
  goldenEmpty:
    'Nessun elemento del set aureo è in attesa della tua valutazione.',
  goldenIntro:
    'Valuta un campione del corso per accuratezza, naturalezza e pertinenza. La media diventa il punteggio pubblico di qualità.',
  goldenUnavailable: 'Il set aureo non è disponibile al momento.',
  growingCourseBanner: 'Nuove unità ogni mese — aiutalo a crescere.',
  haveAccount: 'Hai già un account? Accedi',
  incorrect: 'Non proprio.',
  interfaceLanguage: "Lingua dell'interfaccia",
  journalLabel: 'Scrivi qualche riga',
  journalPrompt1: 'Cosa hai fatto oggi?',
  journalPrompt2: 'Descrivi qualcosa intorno a te ora.',
  journalPrompt3: 'Per cosa sei grato oggi?',
  journalPrompt4: 'Scrivi di qualcuno con cui hai parlato.',
  journalPrompt5: 'Cosa vuoi fare domani?',
  journalSave: 'Salva la nota di oggi',
  journalSaved: 'Salvato. Bel lavoro oggi.',
  journalSuggested: 'Prova a inserire queste parole',
  journalTitle: 'Diario',
  kindLabel: 'Tipo',
  kindPhrase: 'espressione',
  kindSentence: 'frase',
  kindWord: 'parola',
  languageSwitch: 'Cambia lingua',
  lessonWords: '{count} parole',
  listen: 'Ascolta',
  listeningKind: 'Ascolto',
  listeningPrompt: 'Scrivi quello che senti',
  loading: 'Caricamento…',
  manageUsers: 'Gestisci utenti',
  matchPairs: 'abbina le coppie',
  missingWordAria: 'parola mancante',
  morphologyKind: 'Forme della parola',
  myRecordings: 'Le mie registrazioni',
  myRecordingsEmpty: 'Non hai ancora condiviso alcuna registrazione.',
  newHere: 'Sei nuovo qui? Crea un account',
  noCourse: 'Ancora nessun corso — il seme è in arrivo.',
  noDrafts: 'Nessuna bozza in attesa di revisione.',
  noVotes: 'Niente in attesa di voti.',
  notCanonical:
    "Usa l'ortografia standard dell'albanese — lettere come ë e ç sono benvenute.",
  nothingDue: 'Niente da ripassare adesso. Torna più tardi.',
  nothingWeak: 'Ancora nessuna parola debole — continua a imparare.',
  onboardLanguage: 'Che lingua parli già?',
  onboardNote:
    'Nessun account necessario — i tuoi progressi restano su questo dispositivo.',
  onboardTitle: 'Benvenuto',
  openNumbers: 'Numeri aperti',
  password: 'Password',
  planPickUnit: 'Unità di focus',
  planRestNote: 'Riposa — te lo sei meritato.',
  practiceTitle: 'Esercizi',
  priorAuditLabel:
    'Valutazione precedente — accuratezza {accuracy}, naturalezza {naturalness}, pertinenza {fit}.',
  productionKind: 'Scrivi tu',
  productionMiss: 'Usa ogni parola indicata, scritta in forma canonica.',
  productionPrompt: 'Scrivi una frase usando queste parole',
  progressFollows: 'I tuoi progressi ora ti seguono su tutti i dispositivi.',
  qualityScore: 'Punteggio di qualità: {score}/100 ({count} elementi valutati)',
  record: 'Registra',
  recordingFailed: 'Non è stato possibile salvare la registrazione.',
  recordingSaved: 'Registrazione condivisa — grazie.',
  reject: 'Rifiuta',
  reviewDecided: '{count} decise',
  reviewDrafts: 'Revisiona le bozze',
  reviewUnavailable:
    "La coda di revisione non è disponibile — hai effettuato l'accesso come admin?",
  roleAdmin: 'Admin',
  roleLabel: 'Ruolo',
  roleLearner: 'Studente',
  roleReviewer: 'Revisore',
  scriptDrillKind: 'Esercizio di scrittura',
  scriptTypeIn: 'Scrivilo in {script}',
  secondsLeft: '{count} s rimasti',
  selfRateAgain: 'Esercitati ancora',
  selfRateGood: 'Fatto',
  sendForReview: 'Invia in revisione',
  settings: 'Impostazioni',
  signInFailed: 'Email o password errata.',
  signInIssue: 'Qualcosa è andato storto — controlla i dati e riprova.',
  signInTitle: 'Accedi',
  signInToContribute: 'Accedi per contribuire.',
  signInToVote: 'Accedi per votare.',
  signOut: 'Esci',
  signUpFailed:
    "Impossibile creare l'account — l'email potrebbe essere già in uso, o la password è più corta di 8 caratteri.",
  speedReview: 'Ripasso veloce',
  startExercises: 'Inizia gli esercizi',
  startLearning: 'Inizia a imparare',
  statItems: 'Voci del dizionario',
  statLearners: 'Studenti',
  statReviews: 'Ripassi completati',
  statTranslations: 'Traduzioni',
  statsNote: 'Tutto aggregato, niente di personale — il progetto in pubblico.',
  stopRecording: 'Stop',
  streak: 'Serie: {count} giorni',
  submitAudit: 'Salva valutazione',
  submitReview: 'Invia alla revisione della community',
  switchDirection: 'Cambia direzione di apprendimento',
  switchScript: 'Cambia scrittura',
  syncedDown: '{count} ripassi arrivati dagli altri tuoi dispositivi.',
  syncedReviews: '{count} nuovi ripassi sincronizzati da questo dispositivo.',
  tagline: "Impara l'albanese",
  targetLanguageAria: 'albanese',
  targetTextLabel: 'Albanese (ortografia standard)',
  taskJournal: 'Scrivi una nota nel diario',
  taskReviewWeak: 'Ripassa le tue parole deboli',
  taskReviews: 'Rispondi a {count} ripassi',
  taskStudyUnit: 'Studia l’unità {unit}',
  tasksCompleted: '{count} attività completate',
  theme: 'Tema',
  themeDark: 'Scuro',
  themeLight: 'Chiaro',
  themeSystem: 'Sistema',
  timeUp: 'Tempo scaduto.',
  toggleTheme: 'Cambia tema',
  translationLabel: 'Traduzione inglese',
  translationLanguage: 'Lingua di traduzione',
  translationsAria: 'traduzioni',
  typedLabel: 'Scrivilo in albanese — gli accenti sono facoltativi',
  unreachable: 'Il server non è raggiungibile — riprova tra poco.',
  unreachableNow: 'Il server al momento non è raggiungibile.',
  usersUnavailable:
    "L'elenco utenti non è disponibile — hai effettuato l'accesso come admin?",
  voteDown: 'Vota contro',
  voteUp: 'Vota a favore',
  weakItems: 'Parole deboli',
  weekdayFri: 'Venerdì',
  weekdayMon: 'Lunedì',
  weekdaySat: 'Sabato',
  weekdaySun: 'Domenica',
  weekdayThu: 'Giovedì',
  weekdayTue: 'Martedì',
  weekdayWed: 'Mercoledì',
  weeklyPlanTitle: 'Piano settimanale',
  welcome: 'Benvenuti.',
} as const;
