/** Flat Weblate-friendly catalog (ADR 0013); keys stay sorted. */
export const sq = {
  account: 'Llogaria',
  accountOptional:
    'Mësimi funksionon edhe pa llogari — llogaria vetëm sinkronizon përparimin tënd mes pajisjeve.',
  aiDisclosure: 'Hartuar nga IA, shqyrtuar nga njeriu',
  allDone: 'Gjithçka gati.',
  allReviewed: 'Gjithçka u përsërit.',
  answered: '{count} të përgjigjura',
  approve: 'Mirato',
  assemblyBankAria: 'Fjalët',
  assemblyBuiltAria: 'Fjalia jote',
  assemblyKind: 'Ndërto fjalinë',
  back: '← Prapa',
  boardsCleared: 'Tabela të zgjidhura: {count}',
  check: 'Kontrollo',
  clozeLabel: 'Shkruaj fjalën që mungon — thekset nuk janë të detyrueshme',
  codeLicense: 'Kodi: AGPL-3.0-only',
  commonWords: 'Fjalë të shpeshta',
  communityReview: 'Shqyrtimi i komunitetit',
  contentLicense: 'Përmbajtja: CC BY-SA 4.0',
  continueButton: 'Vazhdo',
  contribute: 'Kontribuo',
  contributeFailed: 'Dërgimi dështoi — provo sërish pas pak.',
  contributeLicense:
    "Duke e dërguar, e licencon kontributin tënd nën CC BY-SA 4.0 — licenca e hapur që e mban këtë kurs të lirë për t'u shpërndarë.",
  contributeNote:
    'Gjithçka që shton kalon në shqyrtimin e komunitetit para botimit, nën CC BY-SA 4.0.',
  contributeTitle: 'Propozo një njësi të re',
  contributed: 'U dërgua! Një shqyrtues do ta shohë së shpejti.',
  correct: 'Saktë!',
  createAccount: 'Krijo llogari',
  createTitle: 'Krijo një llogari',
  deleteAccount: 'Fshi llogarinë time',
  deleteConfirm: 'Shtyp edhe një herë që të fshihet gjithçka',
  deleteFailed: 'Fshirja dështoi — provo sërish pas pak.',
  dialogueBankAria: 'Replikat e dialogut',
  dialogueBuiltAria: 'Dialogu yt',
  dialogueReorderKind: 'Rindërto dialogun',
  displayName: 'Emri i shfaqur',
  downloadData: 'Shkarko të dhënat e mia',
  email: 'Email',
  erasedNotice:
    'Llogaria jote dhe të dhënat e saj u fshinë. Përparimi vendor në këtë pajisje mbetet i paprekur.',
  exportFailed: 'Eksportimi dështoi — provo sërish pas pak.',
  fillBlank: 'plotëso vendin bosh',
  formComparative: 'krahasore',
  formPlural: 'shumës',
  formPresent1sg: 'e tashme «unë»',
  formPresent3pl: 'e tashme «ata»',
  formPrompt: 'Shkruaj formën: {form}',
  formSuperlative: 'sipërore',
  haveAccount: 'Ke tashmë llogari? Hyr',
  incorrect: 'Jo tamam.',
  kindLabel: 'Lloji',
  kindPhrase: 'shprehje',
  kindSentence: 'fjali',
  kindWord: 'fjalë',
  languageSwitch: 'Ndërro gjuhën',
  lessonWords: '{count} fjalë',
  listen: 'Dëgjo',
  listeningKind: 'Dëgjim',
  listeningPrompt: 'Shkruaj çfarë dëgjon',
  loading: 'Po ngarkohet…',
  manageUsers: 'Menaxho përdoruesit',
  matchPairs: 'gjej çiftet',
  missingWordAria: 'fjala që mungon',
  morphologyKind: 'Format e fjalës',
  newHere: 'I ri këtu? Krijo një llogari',
  noCourse: 'Ende nuk ka kurs — fara është rrugës.',
  noDrafts: 'Asnjë skicë nuk pret shqyrtim.',
  noVotes: 'Asgjë nuk pret vota.',
  notCanonical:
    'Përdor drejtshkrimin e shqipes standarde — shkronjat ë dhe ç janë të mirëpritura.',
  nothingDue: 'Asgjë nuk të pret tani. Kthehu më vonë.',
  nothingWeak: 'Ende nuk ka fjalë të dobëta — vazhdo mësimin.',
  openNumbers: 'Hap numrat',
  password: 'Fjalëkalimi',
  practiceTitle: 'Ushtrime',
  productionKind: 'Shkruaj vetë',
  productionMiss: 'Përdor çdo fjalë të dhënë, shkruar sipas drejtshkrimit.',
  productionPrompt: 'Shkruaj një fjali duke përdorur këto fjalë',
  progressFollows: 'Përparimi yt tani të ndjek mes pajisjeve.',
  record: 'Regjistro',
  recordingFailed: 'Regjistrimi nuk u ruajt dot.',
  recordingSaved: 'Regjistrimi u nda — faleminderit.',
  reject: 'Refuzo',
  reviewDecided: '{count} të vendosura',
  reviewDrafts: 'Shqyrto skicat',
  reviewUnavailable:
    'Radha e shqyrtimit nuk është e disponueshme — a je futur si administrator?',
  roleAdmin: 'Administrator',
  roleLabel: 'Roli',
  roleLearner: 'Nxënës',
  roleReviewer: 'Shqyrtues',
  scriptDrillKind: 'Ushtrim shkrimi',
  scriptTypeIn: 'Shkruaje me {script}',
  secondsLeft: 'Edhe {count} s',
  selfRateAgain: 'Ushtrohu përsëri',
  selfRateGood: 'E kam',
  sendForReview: 'Dërgo për shqyrtim',
  signInFailed: 'Email ose fjalëkalim i gabuar.',
  signInIssue: 'Nuk funksionoi — kontrollo të dhënat dhe provo sërish.',
  signInTitle: 'Hyr',
  signInToContribute: 'Hyr për të kontribuar.',
  signInToVote: 'Hyr për të votuar.',
  signOut: 'Dil',
  signUpFailed:
    'Llogaria nuk u krijua dot — emaili mund të jetë i zënë, ose fjalëkalimi është më i shkurtër se 8 shenja.',
  speedReview: 'Përsëritje e shpejtë',
  startExercises: 'Fillo ushtrimet',
  startLearning: 'Fillo mësimin',
  statItems: 'Njësi fjalori',
  statLearners: 'Nxënës',
  statReviews: 'Përsëritje të përgjigjura',
  statTranslations: 'Përkthime',
  statsNote: 'Gjithçka e përmbledhur, asgjë personale — projekti në publik.',
  stopRecording: 'Ndalo',
  streak: 'Seria: {count} ditë',
  submitReview: 'Dërgo për shqyrtim nga komuniteti',
  switchScript: 'Ndërro shkrimin',
  syncedDown: '{count} përsëritje erdhën nga pajisjet e tua të tjera.',
  syncedReviews: '{count} përsëritje të reja u sinkronizuan nga kjo pajisje.',
  tagline: 'Mëso shqip',
  targetLanguageAria: 'shqip',
  targetTextLabel: 'Shqip (drejtshkrimi standard)',
  timeUp: 'Koha mbaroi.',
  toggleTheme: 'Ndërro pamjen',
  translationLabel: 'Përkthimi anglisht',
  translationLanguage: 'Gjuha e përkthimit',
  translationsAria: 'përkthime',
  typedLabel: 'Shkruaje shqip — thekset nuk janë të detyrueshme',
  unreachable: 'Serveri nuk arrihet — provo sërish pas pak.',
  unreachableNow: 'Serveri nuk arrihet tani.',
  usersUnavailable:
    'Lista e përdoruesve nuk është e disponueshme — a je futur si administrator?',
  voteDown: 'Voto kundër',
  voteUp: 'Voto pro',
  weakItems: 'Fjalë të dobëta',
  welcome: 'Mirë se vini.',
} as const;
