/**
 * Flat Weblate-friendly catalog (ADR 0013); keys stay sorted.
 *
 * Good-faith draft translation, to be refined by the community via
 * Weblate. Report awkward phrasings rather than working around them.
 */
export const tr = {
  account: 'Hesap',
  accountOptional:
    'Öğrenme hesapsız da çalışır — hesap yalnızca ilerlemeni cihazlar arasında eşitler.',
  aiDisclosure: 'Yapay zekâ taslağı, insan onaylı',
  allDone: 'Gjithçka gati.',
  allReviewed: 'Gjithçka u përsërit.',
  answered: '{count} yanıtlandı',
  approve: 'Onayla',
  assemblyBankAria: 'Kelime havuzu',
  assemblyBuiltAria: 'Cümlen',
  assemblyKind: 'Cümle kur',
  back: '← Geri',
  boardsCleared: 'Çözülen tahtalar: {count}',
  check: 'Kontrol et',
  clozeLabel: 'Eksik kelimeyi yaz — özel harfler zorunlu değil',
  codeLicense: 'Kod: AGPL-3.0-only',
  commonWords: 'Sık kullanılan kelimeler',
  communityReview: 'Topluluk incelemesi',
  contentLicense: 'İçerik: CC BY-SA 4.0',
  continueButton: 'Devam',
  contribute: 'Katkıda bulun',
  contributeFailed: 'Gönderilemedi — birazdan tekrar dene.',
  contributeLicense:
    'Göndererek katkını CC BY-SA 4.0 ile lisanslarsın — bu kursu paylaşıma açık tutan özgür lisans.',
  contributeNote:
    'Eklediğin her şey yayımlanmadan önce CC BY-SA 4.0 altında topluluk incelemesinden geçer.',
  contributeTitle: 'Yeni bir madde öner',
  contributed: 'Gönderildi! Bir inceleyici yakında bakacak.',
  correct: 'Saktë!',
  createAccount: 'Hesap oluştur',
  createTitle: 'Bir hesap oluştur',
  deleteAccount: 'Hesabımı sil',
  deleteConfirm: 'Her şeyi silmek için bir kez daha bas',
  deleteFailed: 'Silme başarısız — birazdan tekrar dene.',
  dialogueBankAria: 'Diyalog satırları',
  dialogueBuiltAria: 'Diyaloğun',
  dialogueReorderKind: 'Diyaloğu yeniden kur',
  displayName: 'Görünen ad',
  downloadData: 'Verilerimi indir',
  email: 'E-posta',
  erasedNotice:
    'Hesabın ve verileri silindi. Bu cihazdaki yerel ilerleme duruyor.',
  exportFailed: 'Dışa aktarma başarısız — birazdan tekrar dene.',
  fillBlank: 'boşluğu doldur',
  formComparative: 'üstünlük',
  formPlural: 'çoğul',
  formPresent1sg: 'şimdiki zaman «ben»',
  formPresent3pl: 'şimdiki zaman «onlar»',
  formPrompt: '{form} biçimini yaz',
  formSuperlative: 'en üstünlük',
  haveAccount: 'Zaten hesabın var mı? Giriş yap',
  incorrect: 'Jo tamam.',
  kindLabel: 'Tür',
  kindPhrase: 'kalıp',
  kindSentence: 'cümle',
  kindWord: 'kelime',
  languageSwitch: 'Dili değiştir',
  lessonWords: '{count} kelime',
  listen: 'Dinle',
  listeningKind: 'Dinleme',
  listeningPrompt: 'Duyduğunu yaz',
  loading: 'Yükleniyor…',
  manageUsers: 'Kullanıcıları yönet',
  matchPairs: 'çiftleri eşleştir',
  missingWordAria: 'eksik kelime',
  morphologyKind: 'Kelime biçimleri',
  newHere: 'Yeni misin? Hesap oluştur',
  noCourse: 'Henüz kurs yok — tohum yolda.',
  noDrafts: 'İnceleme bekleyen taslak yok.',
  noVotes: 'Oy bekleyen bir şey yok.',
  notCanonical:
    'Standart Arnavutça yazımını kullan — ë ve ç gibi harfler hoş karşılanır.',
  nothingDue: 'Şu an tekrar edilecek bir şey yok. Daha sonra tekrar gel.',
  nothingWeak: 'Henüz zayıf kelime yok — öğrenmeye devam et.',
  openNumbers: 'Açık sayılar',
  password: 'Parola',
  practiceTitle: 'Alıştırma',
  productionKind: 'Kendin yaz',
  productionMiss: 'Verilen her kelimeyi kurallı yazımıyla kullan.',
  productionPrompt: 'Bu kelimeleri kullanarak bir cümle yaz',
  progressFollows: 'İlerlemen artık cihazlar arasında seninle geliyor.',
  record: 'Kayıt yap',
  recordingFailed: 'Kayıt kaydedilemedi.',
  recordingSaved: 'Kayıt paylaşıldı — teşekkürler.',
  reject: 'Reddet',
  reviewDecided: '{count} karara bağlandı',
  reviewDrafts: 'Taslakları incele',
  reviewUnavailable:
    'İnceleme kuyruğuna ulaşılamıyor — yönetici olarak giriş yaptın mı?',
  roleAdmin: 'Yönetici',
  roleLabel: 'Rol',
  roleLearner: 'Öğrenci',
  roleReviewer: 'İnceleyici',
  scriptDrillKind: 'Yazı alıştırması',
  scriptTypeIn: '{script} ile yaz',
  secondsLeft: '{count} sn kaldı',
  selfRateAgain: 'Tekrar çalış',
  selfRateGood: 'Anladım',
  sendForReview: 'İncelemeye gönder',
  signInFailed: 'E-posta veya parola yanlış.',
  signInIssue: 'Olmadı — bilgileri kontrol edip tekrar dene.',
  signInTitle: 'Giriş yap',
  signInToContribute: 'Katkıda bulunmak için giriş yap.',
  signInToVote: 'Oy vermek için giriş yap.',
  signOut: 'Çıkış yap',
  signUpFailed:
    'Hesap oluşturulamadı — e-posta alınmış olabilir ya da parola 8 karakterden kısa.',
  speedReview: 'Hızlı tekrar',
  startExercises: 'Alıştırmalara başla',
  startLearning: 'Öğrenmeye başla',
  statItems: 'Sözlük maddeleri',
  statLearners: 'Öğrenciler',
  statReviews: 'Yanıtlanan tekrarlar',
  statTranslations: 'Çeviriler',
  statsNote: 'Her şey toplu, hiçbir şey kişisel değil — proje kamuya açık.',
  stopRecording: 'Durdur',
  streak: '{count} günlük seri',
  submitReview: 'Topluluk incelemesine gönder',
  switchScript: 'Yazıyı değiştir',
  syncedDown: 'Diğer cihazlarından {count} tekrar geldi.',
  syncedReviews: 'Bu cihazdan {count} yeni tekrar eşitlendi.',
  tagline: 'Arnavutça öğren',
  targetLanguageAria: 'Arnavutça',
  targetTextLabel: 'Arnavutça (standart yazım)',
  timeUp: 'Süre doldu.',
  toggleTheme: 'Temayı değiştir',
  translationLabel: 'İngilizce çeviri',
  translationLanguage: 'Çeviri dili',
  translationsAria: 'çeviriler',
  typedLabel: 'Arnavutça yaz — özel harfler zorunlu değil',
  unreachable: 'Sunucuya ulaşılamıyor — birazdan tekrar dene.',
  unreachableNow: 'Sunucuya şu an ulaşılamıyor.',
  usersUnavailable:
    'Kullanıcı listesine ulaşılamıyor — yönetici olarak giriş yaptın mı?',
  voteDown: 'Aleyhte oy ver',
  voteUp: 'Lehte oy ver',
  weakItems: 'Zayıf kelimeler',
  welcome: 'Mirë se vini.',
} as const;
