/** Flat Weblate-friendly catalog (ADR 0013); keys stay sorted. */
export const en = {
  account: 'Account',
  accountOptional:
    'Learning works without one — an account only syncs your progress across devices.',
  aiDisclosure: 'AI-drafted, human-reviewed',
  allDone: 'Vse gotovo.',
  allReviewed: 'Vse pregledano.',
  answered: '{count} answered',
  approve: 'Approve',
  assemblyBankAria: 'Word bank',
  assemblyBuiltAria: 'Your sentence',
  assemblyKind: 'Assemble',
  back: '← Back',
  boardsCleared: 'Boards cleared: {count}',
  check: 'Check',
  clozeLabel: 'Type the missing word — any script, accents optional',
  codeLicense: 'Code: AGPL-3.0-only',
  commonWords: 'Common words',
  communityReview: 'Community review',
  contentLicense: 'Content: CC BY-SA 4.0',
  continueButton: 'Continue',
  contribute: 'Contribute',
  contributeFailed: 'Sending failed — try again in a moment.',
  contributeLicense:
    'By sending, you license your contribution under CC BY-SA 4.0 — the open license that keeps this course free to share.',
  contributeNote:
    'Anything you add goes to community review before it is published, under CC BY-SA 4.0.',
  contributeTitle: 'Suggest a new item',
  contributed: 'Sent! A reviewer will look at it soon.',
  correct: 'Pravilno!',
  createAccount: 'Create account',
  createTitle: 'Create an account',
  deleteAccount: 'Delete my account',
  deleteConfirm: 'Press again to erase everything',
  deleteFailed: 'Deletion failed — try again in a moment.',
  dialogueBankAria: 'Dialogue lines',
  dialogueBuiltAria: 'Your dialogue',
  dialogueReorderKind: 'Rebuild the dialogue',
  displayName: 'Display name',
  downloadData: 'Download my data',
  email: 'Email',
  erasedNotice:
    'Your account and its data are gone. Local progress on this device is untouched.',
  exportFailed: 'Export failed — try again in a moment.',
  fillBlank: 'fill the blank',
  formComparative: 'comparative',
  formPlural: 'plural',
  formPresent1sg: 'present "I"',
  formPresent3pl: 'present "they"',
  formPrompt: 'Type the {form} form',
  formSuperlative: 'superlative',
  goalActiveDays: 'Active days',
  goalJournal: 'Journal entries',
  goalProgress: '{done} / {total}',
  goalReviews: 'Reviews',
  goalsTitle: 'This week',
  haveAccount: 'Already have an account? Sign in',
  incorrect: 'Ne sovsěm.',
  journalLabel: 'Write a few lines',
  journalPrompt1: 'What did you do today?',
  journalPrompt2: 'Describe something around you right now.',
  journalPrompt3: 'What are you grateful for today?',
  journalPrompt4: 'Write about someone you spoke with.',
  journalPrompt5: 'What do you want to do tomorrow?',
  journalSave: "Save today's entry",
  journalSaved: 'Saved. Nice work today.',
  journalSuggested: 'Try weaving in these words',
  journalTitle: 'Journal',
  kindLabel: 'Type',
  kindPhrase: 'phrase',
  kindSentence: 'sentence',
  kindWord: 'word',
  languageSwitch: 'Switch language',
  lessonWords: '{count} words',
  listen: 'Listen',
  listeningKind: 'Listening',
  listeningPrompt: 'Type what you hear',
  loading: 'Loading…',
  manageUsers: 'Manage users',
  matchPairs: 'match the pairs',
  missingWordAria: 'missing word',
  morphologyKind: 'Word forms',
  newHere: 'New here? Create an account',
  noCourse: 'No course yet — the seed is on its way.',
  noDrafts: 'No drafts are waiting for review.',
  noVotes: 'Nothing is waiting for votes.',
  notCanonical:
    'Use canonical etymological Latin — letters like ě, ę, ų, å are welcome.',
  nothingDue: 'Nothing is due right now. Come back later.',
  nothingWeak: 'No weak words yet — keep learning.',
  onboardLanguage: 'Which language do you already speak?',
  onboardNote: 'No account needed — your progress stays on this device.',
  onboardTitle: 'Welcome',
  openNumbers: 'Open numbers',
  password: 'Password',
  planPickUnit: 'Focus unit',
  planRestNote: 'Rest — you have earned it.',
  practiceTitle: 'Practice',
  productionKind: 'Write your own',
  productionMiss: 'Use every prompted word, spelled canonically.',
  productionPrompt: 'Write a sentence using these words',
  progressFollows: 'Your progress now follows you across devices.',
  record: 'Record',
  recordingFailed: 'The recording could not be saved.',
  recordingSaved: 'Recording shared — thank you.',
  reject: 'Reject',
  reviewDecided: '{count} decided',
  reviewDrafts: 'Review drafts',
  reviewUnavailable:
    'The review queue is unavailable — are you signed in as an admin?',
  roleAdmin: 'Admin',
  roleLabel: 'Role',
  roleLearner: 'Learner',
  roleReviewer: 'Reviewer',
  scriptDrillKind: 'Script practice',
  scriptTypeIn: 'Type it in {script}',
  secondsLeft: '{count} s left',
  selfRateAgain: 'Practise again',
  selfRateGood: 'Got it',
  sendForReview: 'Send for review',
  signInFailed: 'Wrong email or password.',
  signInIssue: 'That did not work — check the details and try again.',
  signInTitle: 'Sign in',
  signInToContribute: 'Sign in to contribute.',
  signInToVote: 'Sign in to vote.',
  signOut: 'Sign out',
  signUpFailed:
    'Could not create the account — the email may be taken, or the password is shorter than 8 characters.',
  speedReview: 'Speed review',
  startExercises: 'Start the exercises',
  startLearning: 'Start learning',
  statItems: 'Dictionary items',
  statLearners: 'Learners',
  statReviews: 'Reviews answered',
  statTranslations: 'Translations',
  statsNote: 'Everything aggregate, nothing personal — the project in public.',
  stopRecording: 'Stop',
  streak: '{count}-day streak',
  submitReview: 'Submit to community review',
  switchScript: 'Switch script',
  syncedDown: '{count} reviews arrived from your other devices.',
  syncedReviews: '{count} new reviews synced from this device.',
  tagline: 'Learn Interslavic',
  targetLanguageAria: 'Interslavic',
  targetTextLabel: 'Interslavic (etymological Latin)',
  taskJournal: 'Write a journal entry',
  taskReviewWeak: 'Review your weak words',
  taskReviews: 'Answer {count} reviews',
  taskStudyUnit: 'Study {unit}',
  tasksCompleted: '{count} tasks completed',
  timeUp: 'Time is up.',
  toggleTheme: 'Toggle theme',
  translationLabel: 'English translation',
  translationLanguage: 'Translation language',
  translationsAria: 'translations',
  typedLabel: 'Type it in Interslavic — any script, accents optional',
  unreachable: 'The server is unreachable — try again in a moment.',
  unreachableNow: 'The server is unreachable right now.',
  usersUnavailable:
    'The user list is unavailable — are you signed in as an admin?',
  voteDown: 'Vote against',
  voteUp: 'Vote for',
  weakItems: 'Weak words',
  weekdayFri: 'Friday',
  weekdayMon: 'Monday',
  weekdaySat: 'Saturday',
  weekdaySun: 'Sunday',
  weekdayThu: 'Thursday',
  weekdayTue: 'Tuesday',
  weekdayWed: 'Wednesday',
  weeklyPlanTitle: 'Weekly plan',
  welcome: 'Dobro došli.',
} as const;
