/** Flat Weblate-friendly catalog (ADR 0013); keys stay sorted. */
export const isv = {
  account: 'Konto',
  accountOptional:
    'Učenje funguje bez konta — konto samo synhronizuje tvoj progres prěko uredjenj.',
  aiDisclosure: 'Napisano AI, pregledano člověkom',
  allDone: 'Vse gotovo.',
  allReviewed: 'Vse pregledano.',
  answered: '{count} odgovorjeno',
  approve: 'Odobri',
  assemblyBankAria: 'Slova',
  assemblyBuiltAria: 'Tvoje izrečenje',
  assemblyKind: 'Sklad slov',
  back: '← Nazad',
  boardsCleared: 'Rěšene tablice: {count}',
  check: 'Prověri',
  clozeLabel: 'Napiši nedostajuče slovo — ljuboje pismo, akcenty neobvezny',
  codeLicense: 'Kod: AGPL-3.0-only',
  commonWords: 'Čęsta slova',
  communityReview: 'Pregled komunity',
  contentLicense: 'Sodržanje: CC BY-SA 4.0',
  continueButton: 'Dalje',
  contribute: 'Prispěj',
  contributeFailed: 'Poslanje ne udalo se — probuj znova za moment.',
  contributeLicense:
    'Poslanjem daješ svoj prinos pod otvorenojų licencijų CC BY-SA 4.0.',
  contributeNote:
    'Vse, čto dodaš, ide na pregled komunity prěd publikovanjem, pod CC BY-SA 4.0.',
  contributeTitle: 'Prědloži novu jedinicu',
  contributed: 'Poslano! Pregledatelj skoro to uvidi.',
  correct: 'Pravilno!',
  createAccount: 'Sozdaj konto',
  createTitle: 'Sozdaj konto',
  deleteAccount: 'Izbriši moje konto',
  deleteConfirm: 'Pritisni ješče raz, da by vse bylo izbrisano',
  deleteFailed: 'Izbrisanje ne udalo se — probuj znova za moment.',
  dialogueBankAria: 'Linije dialoga',
  dialogueBuiltAria: 'Tvoj dialog',
  dialogueReorderKind: 'Sostavi dialog znova',
  displayName: 'Pokazyvane ime',
  downloadData: 'Iztegni moje dane',
  email: 'E-mail',
  erasedNotice:
    'Tvoje konto i jegove dane sut izbrisane. Lokalny progres na tom uredjenju ostaje.',
  exportFailed: 'Eksport ne udal se — probuj znova za moment.',
  fillBlank: 'izpolni praznino',
  formComparative: 'komparativ',
  formPlural: 'množina',
  formPresent1sg: 'sejčasno "ja"',
  formPresent3pl: 'sejčasno "oni"',
  formPrompt: 'Napiši formų: {form}',
  formSuperlative: 'superlativ',
  haveAccount: 'Uže imaješ konto? Vojdi',
  incorrect: 'Ne sovsěm.',
  interslavicAria: 'medžuslovjansky',
  isvLabel: 'Medžuslovjansky (etimologična latinica)',
  kindLabel: 'Tip',
  kindPhrase: 'fraza',
  kindSentence: 'rěčenje',
  kindWord: 'slovo',
  languageSwitch: 'Prěključi jezyk',
  lessonWords: '{count} slov',
  listen: 'Slušaj',
  listeningKind: 'Slušanje',
  listeningPrompt: 'Napiši, čto slyšiš',
  loading: 'Zagružaje se…',
  manageUsers: 'Upravjaj uživateljami',
  matchPairs: 'sjedini pary',
  missingWordAria: 'nedostajuče slovo',
  morphologyKind: 'Formy slova',
  newHere: 'Novy tut? Sozdaj konto',
  noCourse: 'Kursa ješče ne jest — sěme jest na putu.',
  noDrafts: 'Nijedin nacrt ne čeka pregleda.',
  noVotes: 'Ničto ne čeka glasov.',
  notCanonical:
    'Piši v kanoničnoj etimologičnoj latinici — bukvy kako ě, ę, ų, å sut dobrodošle.',
  nothingDue: 'Ničto ne čeka sejčas. Vrati se pozdněje.',
  nothingWeak: 'Ješče ne jest slabyh slov — prodolžaj učenje.',
  openNumbers: 'Otvorjena čisla',
  password: 'Parola',
  practiceTitle: 'Praktika',
  progressFollows: 'Tvoj progres sejčas idet s toboju prěko uredjenj.',
  record: 'Zapiši',
  recordingFailed: 'Zapis ne mogl byti shranjeny.',
  recordingSaved: 'Zapis poděljeny — hvala.',
  reject: 'Odkloni',
  reviewDecided: '{count} rěšeno',
  reviewDrafts: 'Pregledaj nacrty',
  reviewUnavailable:
    'Fronta pregleda jest nedostupna — jesi li vpisany kako administrator?',
  roleAdmin: 'Administrator',
  roleLabel: 'Rolja',
  roleLearner: 'Učenik',
  roleReviewer: 'Pregledatelj',
  scriptDrillKind: 'Vprågnjenje pisma',
  scriptToCyrillic: 'Napiši to v kirilici',
  scriptToLatin: 'Napiši to v latinici',
  secondsLeft: 'Ostaje {count} s',
  sendForReview: 'Pošlji na pregled',
  signInFailed: 'Nepravilny e-mail ili parola.',
  signInIssue: 'To ne udalo se — prověri dane i probuj znova.',
  signInTitle: 'Vojdi',
  signInToContribute: 'Vojdi, da by prispěti.',
  signInToVote: 'Vojdi, da by glasovati.',
  signOut: 'Izidi',
  signUpFailed:
    'Ne udalo se sozdati konto — e-mail može byti zanjety, ili parola jest kratša než 8 znakov.',
  speedReview: 'Bystre povtorjenje',
  startExercises: 'Načni vprågnjenja',
  startLearning: 'Načni učenje',
  statItems: 'Slovnikove jedinice',
  statLearners: 'Učenici',
  statReviews: 'Odgovorjena povtorjenja',
  statTranslations: 'Prěvody',
  statsNote: 'Vse jest sborno, ničto osobno — projekt v javnosti.',
  stopRecording: 'Zastavi',
  streak: 'Serija: {count} dni',
  switchScript: 'Prěključi pismo',
  syncedDown: '{count} povtorjenj prišlo s tvojih drugih uredjenj.',
  syncedReviews: '{count} novyh povtorjenj synhronizovano s togo uredjenja.',
  tagline: 'Uči se medžuslovjansky',
  timeUp: 'Vrěme izteklo.',
  toggleTheme: 'Prěključi temu',
  translationLabel: 'Prěvod na anglijsky',
  translationLanguage: 'Jezyk prěvoda',
  translationsAria: 'prěvody',
  typedLabel: 'Napiši medžuslovjansky — ljuboje pismo, akcenty neobvezny',
  unreachable: 'Server jest nedostupny — probuj znova za moment.',
  unreachableNow: 'Server sejčas jest nedostupny.',
  usersUnavailable:
    'Spis uživateljev jest nedostupny — jesi li vpisany kako administrator?',
  voteDown: 'Glasuj protiv',
  voteUp: 'Glasuj za',
  weakItems: 'Slaba slova',
  welcome: 'Dobro došli.',
} as const;
